### ISSUE TITLE
Wait until jobs complete

### ISSUE THREAD

**Issue by Kevinpgalligan** [Frechmatz/cl-threadpool#1]
It appears that there's no way to track jobs once they've been submitted to the pool. How about a function to wait until all jobs in the pool have been completed?

Another option would be to return a "promise" or "future" object from add-job, which comes with a method `get` that waits until the job has completed and then returns the job's output (if any). That's how it's done in Java's concurrency library, if I remember correctly.

**Comment by Frechmatz** [comment]
Thank you for posting the issue. Right now it is up to the jobs to propagate their results. However, a blocking function that returns the result of one or multiple jobs would be a very good feature. I'm working on it, but cannot promise anything yet.

**Comment by Kevinpgalligan** [comment]
Cool! I see it like trying to join a thread. Makes it really convenient to distribute work across multiple threads and then aggregate the results.

Another minor comment. It took me by surprise when I submitted a bunch of jobs to the pool and it crashed due to hitting the max queue size. I would expect there to be no limit, by default. At least, it might be an idea to document the default.

Nice job!

**Comment by Frechmatz** [comment]
Hi there, i would like to ask you, if you could check out the function "run-jobs" of the master branch. It synchronously executes a list of jobs and returns their results. You can find an example here: 
https://github.com/Frechmatz/cl-threadpool/blob/master/test/threadpool/run-jobs-sync.lisp#L3 

BTW: There is an incompatible change in the library: I've removed the option 'resignal-job-conditions' from the pool. I've rethought error handling of jobs and decided to always re-throw unhandled job errors and not to silently handle them.

**Comment by Kevinpgalligan** [comment]
I haven't forgotten about this, I'll take a look this evening if I get the chance.

**Comment by Frechmatz** [comment]
Looking forward to your tests. Please be aware of more (minor) interface changes. All changes are listed in the Change-Log chapter of the Readme.

**Comment by Kevinpgalligan** [comment]
I like the interface! Clean and simple, exactly what I'd expect to find.

I haven't thoroughly checked all of the concurrency logic, but it seems reasonable to me, and the tests look good. Although I find it difficult to ever be 100% confident that concurrent code is correct.

I have 2 questions, just out of curiosity.

1) Is there a reason for putting job locks back in the job lock pool after they've been used? Is that to avoid creating a bunch of throwaway objects when there are many jobs being submitted to the pool? Might be worth capturing that design decision somewhere, maybe a comment.

2) Any reason to use a plist for the locks instead of a class? Might be more convenient if you could write `(set-value job-lock (funcall job))` instead of `(funcall (getf job-lock :set-value) (funcall job))`. I'm relatively new to Common Lisp, so I have no idea.

Really nice work!

**Comment by Frechmatz** [comment]
Thanks for your feedback!

The purpose of the job lock pool is to minimize allocation of system resources such as locks and condition variables. For example if you run 5 jobs and then another 5 jobs, the thread pool allocates 5 locks and cvs instead of 10.

About plists vs. classes: I like the approach to keep state and internal functions inside the execution context of the exposed functions ("let over lambda"). But i'm still undecided about the "best" solution.

**Comment by Frechmatz** [comment]
Version 2.0.0 is now available via Quicklisp

**Comment by Frechmatz** [comment]
Hi :) Version 3.0.0 finally introduces futures.
